version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ecommerce?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password123
      - SPRING_SQL_INIT_MODE=always
      - SPRING_SQL_INIT_PLATFORM=mysql
      # Override with none to disable auto DDL generation, need to manually run schema.sql
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: 'ecommerce'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password123'
      MYSQL_ROOT_PASSWORD: 'password123'
    ports:
      - '3307:3306'
    volumes:
      - ./ecommerce/src/main/resources/db:/app/db
      - my-db:/var/lib/mysql
volumes:
  my-db:
